# Generated by Django 4.2.24 on 2025-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_remove_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_actual',
            field=models.CharField(choices=[('EN_TRANSITO', 'En tránsito'), ('EN_ALISTAMIENTO', 'En alistamiento'), ('POR_VERIFICAR', 'Por verificar'), ('VERIFICADO', 'Verificado'), ('RECHAZADO_VERIFICACION', 'Rechazado por verificación'), ('EMPACADO', 'Empacado'), ('FACTURACION_PENDIENTE', 'Facturación pendiente'), ('FACTURADO', 'Facturado'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto')], default='EN_TRANSITO', max_length=100),
        ),
    ]
