# Generated by Django 3.2.6 on 2025-09-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('valor', models.FloatField()),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
