# Generated by Django 4.2.24 on 2025-09-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_estado_actual'),
        ('ordenDeCompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
        ),
    ]
