# Generated by Django 3.2.6 on 2025-09-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_TRANSITO', 'En tránsito'), ('EN_ALISTAMIENTO', 'En alistamiento'), ('POR_VERIFICAR', 'Por verificar'), ('VERIFICADO', 'Verificado'), ('RECHAZADO_VERIFICACION', 'Rechazado por verificación'), ('EMPACADO', 'Empacado'), ('FACTURACION_PENDIENTE', 'Facturación pendiente'), ('FACTURADO', 'Facturado'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto')], max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
