# Generated by Django 4.2.24 on 2025-09-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_estado_actual'),
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
            preserve_default=False,
        ),
    ]
